// ── Tables ────────────────────────────────────────────────────────────────────
export * from './users.schema';
export * from './user-profiles.schema';
export * from './user-summaries.schema';
export * from './images.schema';
export * from './products.schema';
export * from './scan-history.schema';
export * from './labels.schema';
export * from './ingredients.schema';
export * from './prescriptions.schema';
export * from './medications.schema';
export * from './allergen-flags.schema';
export * from './recommendations.schema';
